// JustSnap - Code Generation Service
// Reference: feature_list.md lines 109-123

import JSZip from 'jszip';
import type { AICodeGeneration } from '../types';

/**
 * Export generated code as ZIP file
 */
export async function exportCodeAsZip(codeGen: AICodeGeneration): Promise<Blob> {
  const zip = new JSZip();

  // Add main component file
  zip.file(codeGen.fileName, codeGen.code);

  // Add styles if present
  if (codeGen.styles) {
    const styleFileName = getStyleFileName(codeGen.framework);
    zip.file(styleFileName, codeGen.styles);
  }

  // Add package.json with dependencies
  if (codeGen.dependencies && codeGen.dependencies.length > 0) {
    const packageJson = {
      name: 'generated-component',
      version: '1.0.0',
      dependencies: Object.fromEntries(codeGen.dependencies.map((dep) => [dep, 'latest'])),
    };
    zip.file('package.json', JSON.stringify(packageJson, null, 2));
  }

  // Add README
  const readme = generateReadme(codeGen);
  zip.file('README.md', readme);

  // Generate ZIP blob
  const blob = await zip.generateAsync({ type: 'blob' });
  return blob;
}

/**
 * Download ZIP file
 */
export function downloadZip(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Get style file name based on framework
 */
function getStyleFileName(framework: string): string {
  switch (framework) {
    case 'react':
    case 'nextjs':
      return 'styles.css';
    case 'vue':
      return 'styles.css';
    case 'flutter':
      return 'theme.dart';
    case 'html':
      return 'styles.css';
    default:
      return 'styles.css';
  }
}

/**
 * Generate README for exported code
 */
function generateReadme(codeGen: AICodeGeneration): string {
  return `# Generated ${codeGen.framework} Component

Generated by JustSnap - AI-Powered Snipping Tool

## Framework: ${codeGen.framework}

## Files Included
- ${codeGen.fileName} - Main component
${codeGen.styles ? `- ${getStyleFileName(codeGen.framework)} - Styles\n` : ''}${
    codeGen.dependencies && codeGen.dependencies.length > 0 ? '- package.json - Dependencies\n' : ''
  }
## Installation

\`\`\`bash
npm install
\`\`\`

## Usage

Import the component in your project and use it as needed.

---

Generated with ❤️ by JustSnap
`;
}
